---
- name: Run Docker container in detached mode and map port 5000
  hosts: testfinal
  become: yes
  tasks:
    - name: Run Docker container
      docker_container:
        name: flask-app
        image: jharajltp/flask-app:latest
        state: started
        detached: yes
        restart_policy: always
        ports:
          - "5000:5000"
